### ISSUE TITLE
Reminders are very broken

### ISSUE THREAD

**Issue by urmilshroff** [urmilshroff/goalkeeper#4]
TODO:
- Need to display reminder time in `GoalsPage`.
- Need to add option to edit reminders in `EditPage`.
- Need to allow multiple reminder notifications (newer ones overwrite already existing ones in the notification shade).
- Need to fix time when reminders are displayed.

TL;DR:
The entire reminders feature is pretty broken, and the code is kind of a mess. This is my first proper Flutter app and I don't really know what I'm doing.

**Comment by ghaith96** [comment]
Hey, this is very interesting, i would like to give it a shot if possible 😀.

**Comment by urmilshroff** [comment]
@ghaith96 Sure! I don't have much time to work on this project due to college work, but I'd love it if someone could fix it. You can fork the repo and send me a pull request with the fixes😁

**Comment by urmilshroff** [comment]
Hey @ghaith96! I've reviewed all of your PRs and everything's working great. Thank you so much!

I wanted to let you know that I've made some minor changes, and will be publishing the update on the [Play Store](https://play.google.com/store/apps/details?id=tech.urmilshroff.goalkeeper) in a couple of hours from now, so you should see it live soon.

Once again, thanks for all the help! Maybe you could check out my other Flutter app, [Dashboard Reborn](https://github.com/urmilshroff/dashboard_reborn) and help with some of those issues, if you'd like to😉
